<?php

namespace Lictevel\MyceliumBundle\Repository;

/**
 * CasejeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasejeuRepository extends \Doctrine\ORM\EntityRepository
{
}
