<?php

namespace Lictevel\MyceliumBundle\Repository;

/**
 * ChampignonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampignonRepository extends \Doctrine\ORM\EntityRepository
{
}
