<?php

namespace Lictevel\MyceliumBundle\Repository;

/**
 * EffetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EffetRepository extends \Doctrine\ORM\EntityRepository
{
}
