<?php

namespace Lictevel\MyceliumBundle\Repository;

/**
 * MutationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MutationRepository extends \Doctrine\ORM\EntityRepository
{
}
