# app/config/routing.yml

lictevel_mycelium_home:
    path: /
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:index }

lictevel_mycelium_a_propos:
    path: /a-propos
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:aPropos }

lictevel_mycelium_connexion:
    path: /connexion
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:connexion }

lictevel_mycelium_deconnexion:
    path: /deconnexion
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:deconnexion }

lictevel_mycelium_inscription:
    path: /inscription
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:inscription }

lictevel_mycelium_mes_champignons:
    path: /mes-champignons
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesChampignons }

lictevel_mycelium_mes_mutations:
    path: /mes-mutations
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesMutations }

lictevel_mycelium_mon_mycelium:
    path: /mon-mycelium
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:monMycelium }

lictevel_mycelium_production:
    path: /production
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:production }

lictevel_mycelium_mes_defenses:
    path: /mes-defenses
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesDefenses }

lictevel_mycelium_statistiques:
    path: /statistiques
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:statistiques }

lictevel_mycelium_mon_compte:
    path: /mon-compte
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:monCompte }

lictevel_mycelium_mes_amis:
    path: /mes-amis
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesAmis }

lictevel_mycelium_caracteristiques_champignon:
    path: /caracteristiques-champi/{id}
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:caracteristiquesChampignon }

lictevel_mycelium_changer_champignon:
    path: /changer-champignon/{id}
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:changerChampignon }
