# app/config/routing.yml

lictevel_mycelium_home:
    path: /
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:index }

lictevel_mycelium_a_propos:
    path: /a-propos
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:aPropos }

lictevel_mycelium_connexion:
    path: /connexion
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:connexion }

lictevel_mycelium_inscription:
    path: /inscription
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:inscription }

lictevel_mycelium_mes_champignons:
    path: /mes-champignons
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesChampignons }

lictevel_mycelium_mes_mutations:
    path: /mes-mutations
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesMutations }

lictevel_mycelium_mon_mycelium:
    path: /mon-mycelium
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:monMycelium }

lictevel_mycelium_production:
    path: /production
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:production }

lictevel_mycelium_mes_defenses:
    path: /mes-defenses
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:mesDefenses }

lictevel_mycelium_statistiques:
    path: /statistiques
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:statistiques }



lictevel_mycelium_view:
    path: /mycelium/{id}
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:view }

lictevel_mycelium_view_slug:
    path: /{year}/{slug}.{format}
    defaults:
      _controller: LictevelMyceliumBundle:Mycelium:viewSlug
      format: html
    requirements:
      year: \d{4}
      format: html|xml

lictevel_mycelium_add:
    path: /add
    defaults: { _controller: LictevelMyceliumBundle:Mycelium:add }

lictevel_mycelium_admin:
  path: /admin
  defaults: { _controller: LictevelMyceliumBundle:Mycelium:admin}
